---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: {{ .Release.Name }}-db
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.connection.db_password }}
            - name: POSTGRESQL_USER
              value: {{ .Values.connection.db_user }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.connection.db_name }}