---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432