---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fhir-service
spec:
  selector:
    app: {{ .Release.Name }}-fhir
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080