---
frontend:
  image: 
    repository: quay.io/jswanepo/hapi-js
    tag: "latest"
    pullPolicy: IfNotPresent

backend:
  image:
    repository: registry.redhat.io/rhel9/postgresql-15
    tag: "latest"
    pullPolicy: IfNotPresent

route:
  termination: edge

connection:
  db_user: admin
  db_password: admin
  db_name: hapi